name = 'Typo'
license = 'MIT'
licenselink = 'https://github.com/tomfran/typo/blob/main/LICENSE'
description = 'A simple Hugo theme'

homepage = 'https://github.com/irostyslav/'

demosite = 'https://irostyslav.github.io/'

tags = [
    "responsive",
    "simple",
    "clean",
    "light",
    "dark",
    "blog",
    "minimal",
    "personal",
    "portfolio",
]

features = [
    "responsive",
    "blog",
    "table-of-contents",
    "highlight.js",
    "favicon",
    "social-icons",
    "minified-assets",
    "dark-light-images",
    "color-palettes",
]

[author]
name = 'Rostyslav Ivanitsa'
homepage = 'https://irostyslav.github.io/'
